#!/bin/sh

brew tap homebrew/cask
brew tap homebrew/cask-versions

brew update
brew upgrade

brew install --cask 1password
brew install --cask alfred
brew install --cask anaconda
brew install --cask bartender
brew install --cask caffeine
brew install --cask docker
brew install --cask dropbox
brew install --cask freedom
brew install --cask handbrake
brew install --cask iterm2
brew install --cask signal
brew install --cask spectacle
brew install --cask sqlectron
brew install --cask whatsapp
brew install --cask visual-studio-code
brew install --cask vlc
brew install --cask zoom

brew cleanup
