#!/bin/sh

brew tap homebrew/core

brew update
brew upgrade

applications=(
    coreutils
    curl
    findutils
    ghq
    gibo
    grep
    jq
    neovim
    node
    sqlite
    tmux
    yarn
    zsh
    zsh-completions
    zsh-syntax-highlighting
)

for application in $applications ; do 
    brew install --upgrade --force $application
done

brew cleanup
