#!/bin/sh

libraries=(
    pandas
    numpy
    scipy
    sympy
    matplotlib
    tensorflow
    keras
    sqlalchemy
    psycopg2
    black
)

env=$HOME/.virtualenvs/base-python
if [[ ! -d $env ]] || [[ -! -f $env/bin/activate ]] ; then 
    virtualenv $env
fi

for lib in $libraries ; do 
    $env/bin/pip3 install $lib
done

echo "source $env/bin/activate" >> ~/.bashrc

