#!/bin/sh

if [[ ! -d $HOME/.venv/neovim ]]; then
  virtualenv "$HOME"/.venv/neovim
  "$HOME"/.venv/neovim/bin/pip install -r "$DOT_DIR"/home/.ven_defs/neovim
fi

if [[ ! -d ~/.config/nvim ]] ; then 
	mkdir -p ~/.config/nvim
fi 

echo """set runtimepath^=~/.vim runtimepath+=~/.vim/after
    let &packpath = &runtimepath
    source ~/.vimrc""" >> ~/.config/nvim/init.vim
