#!/bin/sh

brew tap homebrew/cask
brew tap homebrew/cask-versions

brew update
brew upgrade

brew install --cask 1password
brew install --cask alfred
brew install --cask alt-tab
brew install --cask authy
brew install --cask anaconda
brew install --cask bartender
brew install --cask calibre
brew install --cask caffeine
brew install --cask docker
brew install --cask firefox
brew install --cask handbrake
brew install --cask iterm2
brew install --cask julia
brew install --cask mactex
brew install --cask mediainfo
brew install --cask moom
brew install --cask pdftotext
brew install --cask signal
brew install --cask whatsapp
brew install --cask vlc
brew install --cask zoom

brew cleanup
