#!/bin/sh

brew tap homebrew/core

brew update
brew upgrade

brew install boxes
brew install cmake
brew install cointop
brew install coreutils
brew install curl
brew install exa
brew install findutils
brew install fzf
brew install ghq
brew install gibo
brew install grep
brew install jq
brew install neovim
brew install node
brew install nvm
brew install ocaml
brew install opam
brew install python
brew install ranger
brew install rsync
brew install sqlite
brew install tmux
brew install typescript
brew install yarn
brew install youtube-dl
brew install zsh
brew install zsh-completions
brew install zsh-syntax-highlighting

brew cleanup
