# Some highly opinionated defaults
- defaults:
    link:
      create: true
      relink: true
      glob: true

- clean:
    - "~"
    - "~/Code"

- create:
    - "~/.cron/"
    - "~/Code"
    - "~/Pictures/screenshots/"

- ghq:
    - quinnwinters/quinnwinters.github.io
    - quinnwinters/spark-mmq
    - quinnwinters/dotbot-conda
    - quinnwinters/dotbot-hyper
    - quinnwinters/mathematics-gre

- link:
    ~/.alfred: home/.alfred
    ~/.aliases: home/.aliases
    ~/.automation_scripts: home/.automation_scripts
    ~/.bashrc: home/.bashrc
    ~/.Brewfile: home/.Brewfile
    ~/.conda-env: home/.conda-env
    ~/.cron/jobs: home/.cron/jobs
    ~/.gitconfig: home/.gitconfig
    ~/.gitignore: home/.ignore
    ~/.hyperlayout: home/.hyperlayout
    ~/.mackup: home/.mackup
    ~/.ssh/config: home/.ssh/config
    ~/.tmux.cfg: home/.tmux.cfg
    ~/.tex_templates: home/.tex_templates
    ~/.vim_runtime: home/.vim_runtime
    ~/.vim/init.vim: home/.vim/init.vim
    ~/.vimrc: home/.vimrc
    ~/.zaliases: home/.zaliases
    ~/.zcompletions: home/.zcompletions
    ~/.zshenv: home/.zshenv
    ~/.zshrc: home/.zshrc

- brewfile: [ ~/.Brewfile ] 

- conda-env:
    - "~/.conda-env/data-science.yml"
    - "~/.conda-env/geography.yml"
    - "~/.conda-env/numerics.yml"
    - "~/.conda-env/pyspark.yml"

- hyper:
    - hypercwd
    - hyper-sync-settings
    - hyperlinks
    - hyper-startup
    - hyper-alt-click
    - hyper-search
    - hyper-quit
    - hyper-match
    - hyper-transparent
    - hyper-tab-touchbar
    - hyperterm-visor
    - hyperlayout

- shell:
   - git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
   - vim +PluginInstall +qall
   - sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
   - chsh -s $(which zsh)

