- defaults:
    link:
      force: true
      relink: true
      create: true
    clean:
      force: true
      recursive: true
    shell:
      stdin: true
      stdout: true
      stderr: true

- clean:
    - "~"
    - "~/Code"

- create:
    - "~/Code"
    - "~/Pictures/screenshots/"

- brewfile:
    - home/.Brewfile

- shell:
    - sh scripts/github-ssh.sh
    - sh scripts/macos.sh
    - sh scripts/vundle.sh
    - sh scripts/oh-my-zsh.sh
    - sh scripts/google-drive.sh

- ghqfile:
    - file: home/.ghqrepos
      flags: [-p, --silent, --update]

- link:
    ~/.alfred: home/.alfred
    ~/.aliases: home/.aliases
    ~/.automation: home/.automation
    ~/.bashrc: home/.bashrc
    ~/.Brewfile: home/.Brewfile
    ~/.conda-env: home/.conda-env
    ~/.config/nvim/init.vim: home/.config/nvim/init.vim
    ~/.cron/jobs: home/.cron/jobs
    ~/.ghqrepos: home/.ghqrepos
    ~/.gitconfig: home/.gitconfig
    ~/.gitignore: home/.ignore
    ~/.hyperlayout: home/.hyperlayout
    ~/.ssh/config: home/.ssh/config
    ~/.tmux.cfg: home/.tmux.cfg
    ~/.tex_templates: home/.tex_templates
    ~/.vim_runtime: home/.vim_runtime
    ~/.vim/init.vim: home/.vim/init.vim
    ~/.vimrc: home/.vimrc
    ~/.zaliases: home/.zaliases
    ~/.zcompletions: home/.zcompletions
    ~/.zshenv: home/.zshenv
    ~/.zshrc: home/.zshrc

- conda-env:
    - "~/.conda-env/data-science.yml"
    - "~/.conda-env/geography.yml"
    - "~/.conda-env/numerics.yml"
    - "~/.conda-env/pyspark.yml"

- hyper:
    - hypercwd
    - hyper-sync-settings
    - hyperlinks
    - hyper-startup
    - hyper-alt-click
    - hyper-search
    - hyper-quit
    - hyper-match
    - hyper-transparent
    - hyper-tab-touchbar
    - hyperterm-visor
    - hyperlayout
