- clean:
    - "~"
    - "~/Code"

- create:
    - "~/Code"
    - "~/Pictures/screenshots/"

- link:
    ~/.alfred: home/.alfred
    ~/.aliases: home/.aliases
    ~/.automation_scripts: home/.automation_scripts
    ~/.bashrc: home/.bashrc
    ~/.Brewfile: home/.Brewfile
    ~/.conda-env: home/.conda-env
    ~/.cron/jobs: home/.cron/jobs
    ~/.ghqrepos: home/.ghqrepos
    ~/.gitconfig: home/.gitconfig
    ~/.gitignore: home/.ignore
    ~/.hyperlayout: home/.hyperlayout
    ~/.mackup: home/.mackup
    ~/.ssh/config: home/.ssh/config
    ~/.tmux.cfg: home/.tmux.cfg
    ~/.tex_templates: home/.tex_templates
    ~/.vim_runtime: home/.vim_runtime
    ~/.vim/init.vim: home/.vim/init.vim
    ~/.vimrc: home/.vimrc
    ~/.zaliases: home/.zaliases
    ~/.zcompletions: home/.zcompletions
    ~/.zshenv: home/.zshenv
    ~/.zshrc: home/.zshrc

- brewfile: [ "~/.Brewfile" ] 

- ghqfile: [ "~/.ghqrepos" ]

- conda-env:
    - "~/.conda-env/data-science.yml"
    - "~/.conda-env/geography.yml"
    - "~/.conda-env/numerics.yml"
    - "~/.conda-env/pyspark.yml"

- hyper:
    - hypercwd
    - hyper-sync-settings
    - hyperlinks
    - hyper-startup
    - hyper-alt-click
    - hyper-search
    - hyper-quit
    - hyper-match
    - hyper-transparent
    - hyper-tab-touchbar
    - hyperterm-visor
    - hyperlayout

