#!/usr/bin/env bash

set -e

export GHQ_ROOT=~/Code

CONFIG="install-config.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "$BASEDIR"
git -C "$DOTBOT_DIR" submodule sync --quiet --recursive
git submodule update --init --recursive "$DOTBOT_DIR"

"$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" \
  --verbose \
  -d "$BASEDIR" \
  --plugin-dir dotbot-brew \
  --plugin-dir dotbot-conda \
  --plugin-dir dotbot-ghq \
  -c "$CONFIG" "${@}"
