# Some highly opinionated defaults
- defaults:
    link:
      create: true
      relink: true
      glob: true

- clean:
    - "~"
    - "~/Code"

- create:
    - "~/.cron/"
    - "~/Code"
    - "~/Pictures/screenshots/"

- ghq:
    - quinnwinters/quinnwinters.github.io
    - quinnwinters/spark-mmq
    - quinnwinters/dotbot-conda
    - quinnwinters/dotbot-hyper
    - quinnwinters/mathematics-gre

- link:
    ~/.aliases: home/.aliases
    ~/.automation_scripts: home/.automation_scripts
    ~/.Brewfile: home/.Brewfile
    ~/.conda-env: home/.conda-env
    ~/.cron/jobs: home/.cron/jobs
    ~/.ssh/config: home/.ssh/config
    ~/.tex_templates: home/.tex_templates
    ~/.vim_runtime: home/.vim_runtime
    ~/.vim/init.vim: home/.vim/init.vim
    ~/.gitconfig: home/.gitconfig
    ~/.gitignore: home/.ignore
    ~/.tmux.cfg: home/.tmux.cfg
    ~/.todo.cfg: home/.todo.cfg
    ~/.vimrc: home/.vimrc
    ~/.zshrc: home/.zshrc
    ~/.zaliases: home/.zaliases
    ~/.zcompletions: home/.zcompletions
    ~/.zshenv: home/.zshenv
    ~/.hyperlayout: home/.hyperlayout

- brewfile: [ ~/.Brewfile ] 

- conda-env:
    - "~/.conda-env/data-science.yml"
    - "~/.conda-env/geography.yml"
    - "~/.conda-env/numerics.yml"
    - "~/.conda-env/pyspark.yml"

- hyper:
    - hypercwd
    - hyper-sync-settings
    - hyperlinks
    - hyper-startup
    - hyper-alt-click
    - hyper-search
    - hyper-quit
    - hyper-match
    - hyper-transparent
    - hyper-spotify
    - hyper-window-size
    - hyper-tab-touchbar
    - hyperterm-visor
    - config-hyperterm
    - hyperlayout
    - hypernasa

- shell:
   - git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
   - vim +PluginInstall +qall
   - sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
   - chsh -s $(which zsh)
