#!/usr/bin/env bash

set -e

echo """
   ____        _            _          ____        __  _____ __
  / __ \__  __(_)___  ____ ( )_____   / __ \____  / /_/ __(_) /__  _____
 / / / / / / / / __ \/ __ \|// ___/  / / / / __ \/ __/ /_/ / / _ \/ ___/
/ /_/ / /_/ / / / / / / / / (__  )  / /_/ / /_/ / /_/ __/ / /  __(__  )
\___\_\__,_/_/_/ /_/_/ /_/ /____/  /_____/\____/\__/_/ /_/_/\___/____/

================================================================================================

If this is the first time setting up the computer, you can run 'export DOTBOT_FIRST_RUN=true' to
include the dialogue portions for setting up conneciton to github.com over ssh and the Google Drive
directories. Otherwise the script will begin in 5 seconds
"""

sleep 5s

export GHQ_ROOT=~/Code

if ! which -s brew; then
  echo "No homebrew found, installing via curl/bash"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  brew install brew-file
fi

CONFIG="tooling/configuration.yaml"
DOTBOT_DIR="tooling/dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "$BASEDIR"
git -C "$DOTBOT_DIR" submodule sync --quiet --recursive
git submodule update --init --recursive "$DOTBOT_DIR"

"$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" \
  --verbose \
  -d "$BASEDIR" \
  --plugin-dir tooling/dotbot-brew \
  --plugin-dir tooling/dotbot-conda \
  --plugin-dir tooling/dotbot-ghq \
  --plugin-dir tooling/dotbot-hyper \
  -c "$CONFIG" "${@}"
