# Setup exteneded history and alias to check when command was last run
export HISTFILE=~/.zsh_history
export HISTSIZE=10000000
export SAVEHIST=10000000
HIST_STAMPS="%Y-%m-%d% %T"
setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt SHARE_HISTORY

# Setup neovim as your default editor
export VISUAL=nvim
export EDITOR=$VISUAL
export GIT_EDITOR=$VISUAL
bindkey -e

# Setup ZSH Completions and Highlighting
autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' insert-tab
if [[ ! -f "$HOME/.git-completion.zsh" ]]; then
    curl "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh" >"$HOME/git-completion.zsh"
fi
if [[ -f "$HOME"/.git-completion.zsh ]]; then
    zstyle ':completion:*:*:git:*' script "$HOME"/.git-completion.zsh
fi
if [[ -f /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
    source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

# Better defaults
alias grep='ggrep --color=auto'
alias fgrep='gfgrep --color=auto'
alias diff='diff --color=auto'
alias df='df -h'
alias du='du -h -d 2'
alias date="gdate"

# Sensible piping aliases
alias -g GREP='| grep -i '
alias -g HEAD='| head '
alias -g TAIL='| tail'
alias -g SORT='| sort'
alias -g UNIQUE='| uniq -c'
alias -g DISTINCT='| uniq -c'
alias -g COPY='| pbcopy'
alias -g NOERR='2> /dev/null'
alias -g SILENT='> /dev/null 2>&1'

# if you have zsh configuration files, source them
[[ -d "$HOME/.config/zsh" ]] && for f in $HOME/.config/zsh/**/*.zsh ; do
    echo "Sourcing $f"
    source $f
done

clear

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/usr/local/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2>/dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/usr/local/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]; then
        . "/usr/local/Caskroom/miniconda/base/etc/profile.d/conda.sh"
    else
        export PATH="/usr/local/Caskroom/miniconda/base/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

export STARSHIP_CONFIG="$HOME"/.config/starship/starship.toml
eval $(starship init zsh)

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
