# tap repositories and their packages
tap homebrew/core

# Core tools
brew cmake
brew coreutils
brew curl
brew dateutils
brew exa
brew ffmpeg
brew findutils
brew fpp
brew fzf
brew ghq
brew gibo
brew grep
brew jq
brew mackup
brew mas
brew neovim --HEAD
brew node
brew nvm
brew pyenv
brew pyenv-virtualenv
brew pyenv-virtualenvwrapper
brew python@3.9
brew ranger
brew rsync
brew starship
brew sqlite
brew tmux
brew typescript
brew yarn
brew youtube-dl
brew ydiff
brew zsh
brew zsh-completions
brew zsh-syntax-highlighting

tap homebrew/bundle
tap homebrew/cask-versions
tap homebrew/cask

# Casks
cask 1password
cask anaconda
cask authy
cask bartender
cask bettertouchtool
cask brave-browser
cask caffeine
cask docker
cask dropbox
cask freedom
cask handbrake
cask inkscape
cask iterm2
cask karabiner-elements
cask mactex
cask signal
cask sqlectron
cask vlc
cask zoom

# Brewfile
tap rcmdnk/file
brew brew-file

# App Store applications
appstore 408981434 iMovie (10.2.3)
appstore 784801555 Microsoft OneNote (16.48)
appstore 419330170 Moom (3.2.21)
appstore 360593530 Notability (10.3.4)
appstore 823766827 OneDrive (21.052.0314)
