#!/bin/sh

dot_dir_repo=$(basename `git rev-parse --show-toplevel`)
dot_dir_loc=$(find $HOME -type d -name $dot_dir_repo)

DOT_DIR=$dot_dir_loc
ln -sfn "$DOT_DIR"/home/condarc "$HOME"/.condarc
ln -sfn "$DOT_DIR"/home/editorconfig "$HOME"/.editorconfig
ln -sfn "$DOT_DIR"/home/ghqrepos "$HOME"/.ghqrepos
ln -sfn "$DOT_DIR"/home/gitconfig "$HOME"/.gitconfig
ln -sfn "$DOT_DIR"/home/gitignore "$HOME"/.gitignore
ln -sfn "$DOT_DIR"/home/ssh_config "$HOME"/.ssh/config
ln -sfn "$DOT_DIR"/home/tmux.cfg "$HOME"/.tmux.cfg
ln -sfn "$DOT_DIR"/home/vimrc "$HOME"/.vimrc
ln -sfn "$DOT_DIR"/home/zlogin "$HOME"/.zlogin
ln -sfn "$DOT_DIR"/home/zshrc "$HOME"/.zshrc