#!/bin/bash

instructions="""MANUAL ACTION: GITHUB SSH AUTHENTICATION
----
By default these dotfiles use github over ssh for all operation (for both
security and convenience purposes). You should only have to setup authentication
for github once per computer.
"""

header $instructions
echo "Do you want to continue with setting up github ssh authentication? [Y/n]"
select yn in "Yes" "No"
if [[ $yn  == "Yes" ]] ; then
    echo "Skipping github over ssh setup"
    return
else
    echo "Enter your github email below:"
    read -r email
    ssh-keygen -t rsa -b 4096 -C "$email"
    eval "$(ssh -agent -s)"
    echo "Enter the location of where you stored your key to add it to your ssh agent"
    read -r sshkey
    ssh-add -K "$sshkey"
    pbcopy <"$sshkey"
    echo "Go to https://github.com/settings/keys and paste your key into your ssh key list in settings"
    sleep 10
    echo "When that is done, type verified below"
    while read -r response; do
    case "$response" in
        verified)
        echo "Trust with github should be established!"
        break
        ;;
        *)
        echo "You have not verified that the git-ssh is setup!!"
        echo "Please follow the instructions to continue"
        ;;
    esac
    done
fi
