#!/bin/bash

echo """MANUAL ACTION: GITHUB SSH AUTHENTICATION
----
By default these dotfiles use github over ssh for all operation (for both
security and convenience purposes). You should only have to setup authentication
for github once per computer.
""" | boxes -d simple -p a1l2r2

echo "Do you want to continue with setting up github ssh authentication? [Y/n]"

select yn in "Yes" "No" ; do
    if [[ $yn  == "Yes" ]] ; then 
        echo "Enter your github email below:"
        read -r email
        ssh-keygen -t rsa -b 4096 -C "$email"
        eval "$(ssh -agent -s)"
        echo "Enter the location of where you stored your key to add it to your ssh agent"
        read -r sshkey
        ssh-add -K "$sshkey"
        pbcopy <"$sshkey"
        echo "Go to https://github.com/settings/keys and paste your key into your ssh key list in settings"
        sleep 10
        break
    else
        echo "Skipping setting up github ssh"
	break
    fi
done


