#!/bin/sh

# If Vundle is not installed, install it so that vim doesn't complain when linking vimrc
if [[ ! -d "$HOME"/.vim/bundle/Vundle.vim ]]; then
  mkdir -p "$HOME"/.vim/bundle
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

DOT_DIR=$(git rev-parse --show-toplevel)
ln -sfn "$DOT_DIR"/home/condarc "$HOME"/.condarc
ln -sfn "$DOT_DIR"/home/editorconfig "$HOME"/.editorconfig
ln -sfn "$DOT_DIR"/home/ghqrepos "$HOME"/.ghqrepos
ln -sfn "$DOT_DIR"/home/gitconfig "$HOME"/.gitconfig
ln -sfn "$DOT_DIR"/home/gitignore "$HOME"/.gitignore
ln -sfn "$DOT_DIR"/home/mackup.cfg "$HOME"/.mackup.cfg
ln -sfn "$DOT_DIR"/home/rc.conf "$HOME"/.config/ranger/rc.conf
ln -sfn "$DOT_DIR"/home/ssh_config "$HOME"/.ssh/config
ln -sfn "$DOT_DIR"/home/tmux.cfg "$HOME"/.tmux.cfg
ln -sfn "$DOT_DIR"/home/vimrc "$HOME"/.vimrc
ln -sfn "$DOT_DIR"/home/zlogin "$HOME"/.zlogin
ln -sfn "$DOT_DIR"/home/zshrc "$HOME"/.zshrc
