#!/bin/sh

if [[ -d /Applications/OneDrive.app ]] ; then
    header """Microsoft OneDrive Sync
About to setup authentication with Microsoft OneDrive and link folders up. If you
have already set this up you should skip this step
    """

    echo "Would you like to setup OneDrive sync?"
    select yn in "Yes" "No"
    if [[ $yn == "Yes" ]] ; then
        echo "Opening the applications folder in finder. You have to authenticate with OneDrive Manually"
        open /Applications
        sleep 15
        echo "When that is done, type verified below"
        while read -r response; do
        case "$response" in
            verified)
            echo "Authentication with OneDrive Established!"
            break
            ;;
            *)
            echo "You have not verified that the OneDrive is setup!!"
            echo "Please follow the instructions to continue"
            ;;
        esac
    else
        echo "Skipping OneDrive setup"
    fi
fi
